apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-argocd-s3-localstack-bucket-
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: localstack-aws
