---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-static-site
  namespace: argocd
  labels:
    crossplane.atrakic.github.io: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/atrakic/go-static-site
    targetRevision: HEAD
    path: charts/go-static-site
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 5
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m
